(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('sea'), ctx=canvas.getContext('2d'), mini=$('minimap').getContext('2d');
const C=Combat, TAU=Math.PI*2, YCOMP=.76, ZS=.34, ZR=.88, HULL=[[-176,-55],[-132,-72],[75,-64],[185,0],[75,64],[-132,72],[-176,55]];
const PLAYER_X=920, PLAYER_Y=1060, PLAYER_SCALE=1.75, AUTO_SPEED=105, VOLLEY_RELOAD=12, MAX_OPEN=2, MAX_ACTIVE_SHIPS=5, SWARM_TOTAL=14, ALLIED_SHOOTERS=60, ALLIED_DEFENDERS=60, ACTIVE_BOARDER_CAP=220, DECK_PRESSURE_LIMIT=140;
const DECK={upperEntry:{x:38,y:-48},lowerEntry:{x:38,y:48},center:{x:-12,y:0},cabin:{x:-112,y:0},upperGun:{x:44,y:-46},lowerGun:{x:44,y:46}};
const DEF_ZONES={upper:{x:15,y:-39},center:{x:-6,y:0},lower:{x:15,y:39}};
const SHOOTERS=Array.from({length:ALLIED_SHOOTERS},(_,i)=>{
 const cols=12,row=Math.floor(i/cols),col=i%cols;
 return{kind:i%3===2?'musket':'bow',x:-132+col*20.5+(row%2?5:0),y:-34+row*17};
});
const WAVES=[
 {at:3,label:'双艇试探',spawns:[{type:'skiff',side:'upper'},{type:'skiff',side:'lower',delay:4}]},
 {at:38,label:'小艇连续压迫',spawns:[{type:'skiff',side:'lower'},{type:'skiff',side:'upper',delay:5},{type:'skiff',side:'lower',delay:11}]},
 {at:80,label:'掩护艇带队',spawns:[{type:'support',side:'upper'},{type:'skiff',side:'lower',delay:3},{type:'skiff',side:'upper',delay:10}]},
 {at:125,label:'中艇突破',spawns:[{type:'medium',side:'upper'},{type:'skiff',side:'lower',delay:5}]},
 {at:175,label:'大船压舷',spawns:[{type:'large',side:'lower'},{type:'skiff',side:'upper',delay:9}]},
 {at:235,label:'小艇收尾围攻',spawns:[{type:'skiff',side:'upper'},{type:'skiff',side:'lower',delay:8}]}
];
const SHIP_CFG={
 skiff:{name:'快速运兵艇',hp:165,speed:102,crew:30,boarders:40,connectHp:72,size:.72,range:780},
 support:{name:'远程掩护艇',hp:170,speed:88,crew:50,boarders:20,connectHp:70,size:.78,range:920,support:true},
 medium:{name:'中型运兵船',hp:330,speed:78,crew:50,boarders:80,connectHp:115,size:.9,range:850},
 large:{name:'大型登船舰',hp:540,speed:62,crew:70,boarders:140,connectHp:125,size:1.08,range:900,connections:2}
};
const LIGHT_RANGE={bow:720,musket:820};
let width=0,height=0,scale=1,dpr=1,raf=0,last=0,sound=false,audio=null,debug=false,state;
const rand=(a,b)=>a+Math.random()*(b-a), clamp=C.clamp;
function resize(){width=innerWidth;height=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=width+'px';canvas.style.height=height+'px';scale=Math.max(width/1580,height/900);ctx.setTransform(dpr,0,0,dpr,0,0);}
function tone(f=220,d=.05,g=.025,type='triangle'){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),q=audio.createGain();o.type=type;o.frequency.value=f;q.gain.value=g;q.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(q);q.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{sound=false;}}
function project(x,y,z=0){const camX=state?state.cameraX:470,camY=state?state.cameraY:465;return{x:(x-camX)*scale+z*ZS*scale,y:(y-camY)*scale*YCOMP-z*ZR*scale};}
function worldLocal(ship,lx,ly){const k=ship.team==='player'?PLAYER_SCALE:1,c=Math.cos(ship.a),s=Math.sin(ship.a),x=lx*k,y=ly*k;return{x:ship.x+c*x-s*y,y:ship.y+s*x+c*y};}
function localOf(ship,x,y){const k=ship.team==='player'?PLAYER_SCALE:1,dx=x-ship.x,dy=y-ship.y,c=Math.cos(-ship.a),s=Math.sin(-ship.a);return{x:(dx*c-dy*s)/k,y:(dx*s+dy*c)/k};}
function shipPt(ship,lx,ly,z=0){const p=worldLocal(ship,lx,ly);return project(p.x,p.y,z-(ship.sink||0)*95);}
function toast(text,t=2){$('toast').textContent=text;state.toast=t;}
function alloc(arr,max=450){if(arr.length>max)arr.splice(0,arr.length-max);}
function burst(x,y,color,n=8,power=50,type='smoke',z=20){for(let i=0;i<n;i++){const a=rand(0,TAU),v=rand(12,power);state.fx.push({x,y,z:z+rand(0,10),vx:Math.cos(a)*v,vy:Math.sin(a)*v,vz:type==='water'?rand(55,120):rand(12,55),life:rand(.35,.8),max:.8,r:rand(2,5),color,type,rot:rand(0,TAU),vr:rand(-5,5)});}alloc(state.fx,420);}
function splash(x,y){burst(x,y,'#dffaff',13,48,'water',0);}
function floatText(x,y,text,color='#f3e8c8',size=12,key=''){const old=key&&state.texts.find(t=>t.key===key&&t.life>.45);if(old&&/^\d+$/.test(String(text))&&/^\d+$/.test(String(old.text))){old.text=String(Number(old.text)+Number(text));old.life=.9;return;}state.texts.push({x,y,text:String(text),color,size,life:1,key});alloc(state.texts,24);}
function makeShooter(i){const b=SHOOTERS[i];return{id:'pS'+i,team:'player',kind:b.kind,lx:b.x,ly:b.y,homeLx:b.x,homeLy:b.y,motionId:i,x:b.x,y:b.y,hp:b.kind==='musket'?38:31,maxHp:b.kind==='musket'?38:31,alive:true,cd:.15+i*(b.kind==='bow'?.21:.37),action:'idle',timer:0,facing:0,recoil:0,role:'shooter'};}
function makeDefender(i,side,reserve=false){
 const group=reserve?i-40:side==='lower'?i-20:i;let x,y;
 if(reserve){x=-86+(group%10)*18;y=Math.floor(group/10)===0?-15:15;}
 else{x=-96+(group%10)*20;const row=Math.floor(group/10);y=(side==='upper'?-1:1)*(45-row*12);}
 return{id:'pD'+i,team:'player',kind:'melee',lx:x,ly:y,homeLx:x,homeLy:y,motionId:i,x,y,hp:72,maxHp:72,alive:true,down:false,reserve,zone:reserve?'center':side,targetZone:reserve?'center':side,cd:.2+(i%10)*.045,action:'idle',timer:0,facing:0,role:'melee',rescue:0};
}
function playerShip(){
 const p={id:0,team:'player',x:PLAYER_X,y:PLAYER_Y,a:0,hp:520,maxHp:520,water:0,sail:100,sink:0,dead:false,gunHp:{upper:150,lower:150},gunMax:150,breaches:[],recoil:{upper:0,lower:0}};
 p.shooters=Array.from({length:ALLIED_SHOOTERS},(_,i)=>makeShooter(i));
 p.defenders=[...Array.from({length:20},(_,i)=>makeDefender(i,'upper')),...Array.from({length:20},(_,i)=>makeDefender(i+20,'lower')),...Array.from({length:20},(_,i)=>makeDefender(i+40,'center',true))];
 return p;
}
function enemyCrew(ship,i){
 const kind=i%3===2?'musket':'bow',cols=10,row=Math.floor(i/cols),col=i%cols;
 const lx=-82+col*18+(row%2?4:0),ly=clamp(-32+row*10,-34,34);
 return{id:`e${ship.id}c${i}`,team:'enemy',kind,hp:kind==='musket'?28:24,maxHp:kind==='musket'?28:24,alive:true,cd:.18+(i%9)*.055,lx,ly,homeLx:lx,homeLy:ly,motionId:i,facing:Math.PI,action:'idle',timer:0,recoil:0};
}
function roster(type,n){
 const arr=[];
 for(let i=0;i<n;i++){
  let kind='assault';
  if(type==='large'){if(i<28)kind='shield';else if(i%7===0)kind='breaker';}
  else if(type==='medium'){if(i<12)kind='shield';else if(i%6===0)kind='breaker';}
  else if(type==='skiff'){if(i<8)kind='shield';else if(i%9===0)kind='breaker';}
  else if(type==='support'){if(i<4)kind='shield';else if(i%5===0)kind='breaker';}
  arr.push(kind);
 }
 return arr;
}
let nextShipId=1,nextUnitId=1;
function makeEnemy(type,side,spawnOffset=0){const cfg=SHIP_CFG[type],sign=side==='upper'?-1:1,x=PLAYER_X+1180+spawnOffset,y=PLAYER_Y+sign*410;const ship={id:nextShipId++,team:'enemy',type,cfg,x,y,a:Math.PI,hp:cfg.hp,maxHp:cfg.hp,speed:cfg.speed,side,phase:'approach',approachStage:'ranged',phaseTime:0,targetX:PLAYER_X+80,targetY:PLAYER_Y+sign*155,removed:false,sinking:false,sink:0,sinkTimer:0,crew:[],boarderRoster:roster(type,cfg.boarders),launched:0,remaining:cfg.boarders,connections:[],fireCd:.18+rand(0,.45),tagTime:3,withdraw:false,recoil:{upper:0,lower:0}};ship.crew=Array.from({length:cfg.crew},(_,i)=>enemyCrew(ship,i));const count=cfg.connections||1;for(let i=0;i<count;i++){const offset=count===2?(i===0?-54:54):0;ship.connections.push({id:`conn${ship.id}:${i}`,shipId:ship.id,side,slot:i,offset,progress:0,hp:cfg.connectHp,maxHp:cfg.connectHp,phase:'idle',open:false,broken:false,queue:[],crossing:[],spawnCd:0,prep:0});}return ship;}
function makeBoarder(ship,conn,kind,index){
 const sign=ship.side==='upper'?-1:1,lane=((index%8)-3.5)*4.5;
 const start=worldLocal(ship,-38+(index%6)*11+conn.offset*.35,-sign*(48+lane*.22));
 return{id:nextUnitId++,team:'enemy',kind,shipId:ship.id,connectionId:conn.id,state:'enemyDeck',x:start.x,y:start.y,z:30,lx:0,ly:0,hp:kind==='shield'?92:kind==='breaker'?62:55,maxHp:kind==='shield'?92:kind==='breaker'?62:55,cd:rand(.2,.6),facing:Math.PI,progress:0,dead:false,fall:false,prep:0,targetFacility:null,hitFlash:0};
}
function stats(){return{lightFired:0,lightHits:0,cannonFired:0,cannonHits:0,boarded:0,boardersKilled:0,connectionsBroken:0,shipsSunk:0,damageTaken:0,maxUnits:0,maxProjectiles:0,maxFx:0,maxTexts:0};}
function resetGuard(variant=state?.variant||0){nextShipId=1;nextUnitId=1;const p=playerShip();state={mode:'guard',variant:variant%3,player:p,enemies:[],boarders:[],shots:[],lightShots:[],fx:[],texts:[],cannonQueue:[],time:0,scroll:0,waveIndex:0,pending:[],paused:false,end:null,toast:3,shake:0,volley:0,volleyMax:VOLLEY_RELOAD,repair:0,repairUses:2,targetShipId:null,targetBoarderId:null,reserveZone:'center',cameraX:300,cameraY:430,metrics:stats(),openEntrances:0,settle:0,nextSafeWindow:0};setupGuardUI();$('overlay').classList.add('hidden');$('pause').textContent='Ⅱ';toast('持续航行 · 先远程交火，敌船会逐步逼近再靠舷',3);updateHud();}
function setupGuardUI(){document.title='蔚蓝航路 · 持续航行·甲板守卫战';$('sceneNameTop').textContent='持续航行航线';$('missionTitle').textContent='甲板守卫';$('missionText').textContent='远程交火 → 敌船逼近 → 靠舷登船 → 调兵守甲板 → 重炮断援';const tabs=document.querySelector('.scenario-tabs');if(tabs)tabs.innerHTML='<button class="active">甲板守卫</button>';const lt=document.querySelector('.layout-tools');if(lt)lt.innerHTML='<button id="retryGuard">重试本局</button><button id="changeGuard">更换布局</button>';if($('retryGuard'))$('retryGuard').onclick=()=>resetGuard(state.variant);if($('changeGuard'))$('changeGuard').onclick=()=>resetGuard(state.variant+1);document.querySelector('.controls').innerHTML='<div class="defense-pad" id="defensePad"><button data-zone="upper">上舷</button><button data-zone="center" class="active">中央</button><button data-zone="lower">下舷</button></div><span class="move-hint">预备队调度 · 只移动20名预备近战</span>';document.querySelector('.focus-panel').innerHTML='<span>预备队调度</span><div><button data-zone="upper">上舷</button><button data-zone="center" class="active">中央</button><button data-zone="lower">下舷</button></div>';document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>setReserveZone(b.dataset.zone));$('boost').style.display='none';$('volley').querySelector('strong').textContent='舰炮齐射';$('volleyCd').textContent='SPACE · 重炮就绪';$('repairCd').textContent='R · 2次';$('aimStatus').textContent='点击敌船选择舰炮目标';$('targetStatus').textContent='点击甲板敌人指定优先集火';$('speedText').textContent='自动航行 8 kn';const inst=$('instructions');inst.innerHTML='<p><b>守卫</b> 我船自动向右航行。点击上舷／中央／下舷调动20名预备近战，预备队会实际沿甲板移动。</p><p><b>集火</b> 点击海上敌船选择重炮目标；点击登船敌人指定射手和守军优先处理。</p><p><b>舰炮</b> SPACE／右下按钮。开局可用，基础装填约12秒；只有目标位于有效侧舷且对应炮位可用时才发射。</p><p><b>连接</b> 敌船先靠舷，再抛钩／搭跳板，敌人依次通过。全场最多两个主要入口。</p><p><b>兵种</b> 盾兵顶箭火，突击兵抢入口，破坏兵会绕向炮位或船舱，准备后才造成结构伤害。</p><p><b>维修</b> R有限2次，恢复部分船体并修复受损设施，不能复活所有倒地人员。</p>';}
function setReserveZone(zone){if(!DEF_ZONES[zone])return;state.reserveZone=zone;for(const d of state.player.defenders)if(d.reserve)d.targetZone=zone;document.querySelectorAll('[data-zone]').forEach(b=>b.classList.toggle('active',b.dataset.zone===zone));toast('预备队前往'+(zone==='upper'?'上舷':zone==='lower'?'下舷':'中央'),1.25);}
function spawnWave(w){let delayed=0;for(const spec of w.spawns){const delay=spec.delay||0;state.pending.push({at:state.time+delay,type:spec.type,side:variantSide(spec.side),wave:w.label});delayed=Math.max(delayed,delay);}toast('发现敌情 · '+w.label,2.2);}
function variantSide(side){if(state.variant===1)return side==='upper'?'lower':'upper';if(state.variant===2&&Math.random()<.45)return side==='upper'?'lower':'upper';return side;}
function activeThreats(){return state.enemies.filter(e=>!e.removed&&!e.sinking).length;}
function deckEnemyCount(){return state.boarders.filter(b=>!b.dead&&(b.state==='deck'||b.state==='crossing')).length;}
function processWaves(){if(state.waveIndex<WAVES.length&&state.time>=WAVES[state.waveIndex].at){if(deckEnemyCount()<=DECK_PRESSURE_LIMIT&&state.openEntrances<MAX_OPEN){spawnWave(WAVES[state.waveIndex]);state.waveIndex++;}else return;}for(let i=state.pending.length-1;i>=0;i--){const p=state.pending[i];if(state.time>=p.at&&activeThreats()<MAX_ACTIVE_SHIPS){const ship=makeEnemy(p.type,p.side,rand(-80,120));state.enemies.push(ship);state.pending.splice(i,1);}}}
function connectionWorld(ship,conn,playerSide=false){const sign=ship.side==='upper'?-1:1;if(playerSide){const local={x:38+conn.offset*.55,y:sign*55};return worldLocal(state.player,local.x,local.y);}const local={x:-25+conn.offset*.35,y:-sign*58};return worldLocal(ship,local.x,local.y);}
function openCount(exclude=null){return state.enemies.flatMap(e=>e.connections).filter(c=>c!==exclude&&!c.broken&&(c.open||c.phase==='building')).length;}
function updateEnemyShip(ship,dt){
 if(ship.removed)return;
 if(ship.sinking){ship.sinkTimer+=dt;ship.sink=clamp(ship.sinkTimer/3.5,0,1);ship.x-=35*dt;if(Math.random()<dt*8)splash(ship.x+rand(-60,60),ship.y+rand(-28,28));if(ship.sink>=1){ship.removed=true;state.metrics.shipsSunk++;}return;}
 ship.tagTime=Math.max(0,ship.tagTime-dt);ship.fireCd-=dt;const sign=ship.side==='upper'?-1:1;
 updateEnemyCrewMotion(ship,dt);
 if(ship.phase==='approach'){
  const tx=PLAYER_X+120+(ship.type==='support'?240:0),ty=PLAYER_Y+sign*(ship.type==='support'?305:210);
  const dx=tx-ship.x,dy=ty-ship.y,d=Math.hypot(dx,dy)||1;
  ship.approachStage=C.guardApproachStage(d);
  const v=C.guardApproachSpeed(ship.type,d);
  ship.x+=dx/d*v*dt;ship.y+=dy/d*v*dt;
  ship.a=C.rotateToward(ship.a,0,dt*.72);
  if(d<58){ship.phase=ship.cfg.support?'support':'align';ship.phaseTime=0;}
 }
 else if(ship.phase==='align'){
  ship.approachStage='align';ship.phaseTime+=dt;
  ship.x+=(PLAYER_X+80-ship.x)*dt*.42;ship.y+=(PLAYER_Y+sign*210-ship.y)*dt*.4;
  if(ship.phaseTime>1.65){const possible=ship.connections.find(c=>!c.broken&&c.phase==='idle');if(possible&&C.connectionOpenAllowed(openCount(possible),MAX_OPEN)){possible.phase='building';ship.phase='connect';ship.phaseTime=0;toast(ship.cfg.name+' 开始建立'+(ship.side==='upper'?'上舷':'下舷')+'连接',1.7);}else ship.phase='waiting';}
 }
 else if(ship.phase==='waiting'){ship.approachStage='waiting';ship.x+=Math.sin(state.time*.8+ship.id)*5*dt;ship.y+=(PLAYER_Y+sign*285-ship.y)*dt*.32;if(C.connectionOpenAllowed(openCount(),MAX_OPEN)){ship.phase='align';ship.phaseTime=0;}}
 else if(ship.phase==='connect'||ship.phase==='boarding'){
  ship.approachStage='alongside';ship.x+=(PLAYER_X+80-ship.x)*dt*.5;ship.y+=(PLAYER_Y+sign*210-ship.y)*dt*.5;let any=false;
  for(const c of ship.connections){if(c.broken)continue;if(c.phase==='building'){c.progress=C.boardingAdvance(c.progress,dt,2.25+(ship.type==='large'?0.6:0));if(c.progress>=1){c.phase='open';c.open=true;state.openEntrances=openCount();ship.phase='boarding';c.spawnCd=.25;toast('跳板已架好 · '+(ship.side==='upper'?'上舷':'下舷')+'开始登船',1.5);}any=true;}else if(c.open){any=true;updateConnectionBoarding(ship,c,dt);}}
  if(ship.phase==='boarding'&&ship.type==='large'&&ship.connections.length>1){const second=ship.connections[1];if(!second.broken&&second.phase==='idle'&&ship.launched>=28&&C.connectionOpenAllowed(openCount(),MAX_OPEN)){second.phase='building';second.progress=0;toast('大型登船舰准备第二处连接',1.4);}}
  if(!any||ship.remaining<=0&&ship.connections.every(c=>c.crossing.length===0)){for(const c of ship.connections){if(!c.broken){c.open=false;c.phase='idle';c.progress=0;}}ship.phase='withdraw';ship.phaseTime=0;}
 }
 else if(ship.phase==='support'){ship.approachStage='ranged';ship.x+=(PLAYER_X+300-ship.x)*dt*.22;ship.y+=(PLAYER_Y+sign*300-ship.y)*dt*.22;if(ship.hp<ship.maxHp*.45)ship.phase='withdraw';}
 else if(ship.phase==='withdraw'){ship.approachStage='withdraw';ship.phaseTime+=dt;ship.x+=125*dt;ship.y+=sign*24*dt;if(ship.x>PLAYER_X+1250)ship.removed=true;}
 const range=Math.hypot(ship.x-PLAYER_X,ship.y-PLAYER_Y);
 if(!ship.sinking&&ship.phase!=='withdraw'&&ship.fireCd<=0&&range<ship.cfg.range){const rangedCadence=ship.approachStage==='ranged'?rand(.26,.46):rand(.3,.52);ship.fireCd=rangedCadence;enemyLightFire(ship);}
}
function updateConnectionBoarding(ship,conn,dt){
 if(conn.broken||!conn.open)return;
 conn.spawnCd-=dt;
 let activeBoarders=0,inTransit=0;
 for(const b of state.boarders){
  if(b.dead)continue;
  if(b.state==='enemyDeck'||b.state==='crossing'||b.state==='deck')activeBoarders++;
  if(b.connectionId===conn.id&&(b.state==='enemyDeck'||b.state==='crossing'))inTransit++;
 }
 if(activeBoarders>=ACTIVE_BOARDER_CAP){conn.spawnCd=Math.max(conn.spawnCd,.12);return;}
 const lanes=ship.type==='large'?12:8;
 if(conn.spawnCd<=0&&ship.remaining>0&&inTransit<lanes){
  const kind=ship.boarderRoster[ship.launched]||'assault',b=makeBoarder(ship,conn,kind,ship.launched);
  state.boarders.push(b);ship.launched++;ship.remaining--;
  conn.spawnCd=ship.type==='large'?.11:.14;
 }
}
function updateEnemyCrewMotion(ship,dt){
 for(const c of ship.crew){if(!c.alive)continue;c.recoil=Math.max(0,(c.recoil||0)-dt);if(c.timer>0){c.timer-=dt;if(c.timer<=0)c.action='idle';}
  const off=C.crewMotionOffset(c.motionId,state.time,'enemy'),goal={x:c.homeLx+off.x,y:c.homeLy+off.y};
  const mv=C.reserveStep({x:c.lx,y:c.ly},goal,c.action==='fire'?8:14,dt);c.lx=mv.x;c.ly=mv.y;
  if(c.action!=='fire'){const from=worldLocal(ship,c.lx,c.ly);c.facing=Math.atan2(PLAYER_Y-from.y,PLAYER_X-from.x);}
 }
}
function enemyLightFire(ship){const crew=ship.crew.filter(c=>c.alive);if(!crew.length)return;const c=crew[Math.floor(Math.random()*crew.length)],from=worldLocal(ship,c.lx,c.ly),targets=[...state.player.shooters,...state.player.defenders].filter(u=>u.alive&&!u.down);if(!targets.length)return;let t=null,bd=Infinity;for(const u of targets){const dd=threatDistance(ship,u);if(dd<bd){bd=dd;t=u;}}if(!t)return;const to=worldLocal(state.player,t.lx,t.ly);c.facing=Math.atan2(to.y-from.y,to.x-from.x);c.action='fire';c.timer=c.kind==='musket'?.22:.16;c.recoil=c.kind==='musket'?.18:.08;spawnLight(c.kind,from,to,true,{ship,crew:c,target:t});}
function threatDistance(ship,u){const p=worldLocal(state.player,u.lx,u.ly);return Math.hypot(p.x-ship.x,p.y-ship.y);}
function nearestPlayerTarget(from){
 const deck=state.boarders.filter(b=>!b.dead&&(b.state==='crossing'||b.state==='deck'));
 if(state.targetBoarderId){const m=deck.find(b=>b.id===state.targetBoarderId);if(m)return m;}
 let best=null,bd=Infinity;
 for(const b of deck){const dx=b.x-from.x,dy=b.y-from.y,dd=dx*dx+dy*dy;if(dd<bd){bd=dd;best=b;}}
 if(best)return best;
 for(const s of state.enemies)if(!s.removed&&!s.sinking)for(const c of s.crew)if(c.alive){const p=worldLocal(s,c.lx,c.ly),dx=p.x-from.x,dy=p.y-from.y,dd=dx*dx+dy*dy;if(dd<bd){bd=dd;best={ship:s,crew:c,x:p.x,y:p.y,z:36,remote:true};}}
 return best;
}
function updateShooters(dt){for(const s of state.player.shooters){if(!s.alive)continue;const closeThreat=state.boarders.find(b=>!b.dead&&b.state==='deck'&&Math.hypot(b.lx-s.lx,b.ly-s.ly)<34);const off=C.crewMotionOffset(s.motionId,state.time,'shooter'),idlePost={x:s.homeLx+off.x,y:s.homeLy+off.y};if(closeThreat){const retreat={x:Math.max(-145,s.homeLx-30),y:clamp(s.homeLy*.55,-28,28)},mv=C.reserveStep({x:s.lx,y:s.ly},retreat,36,dt);s.lx=mv.x;s.ly=mv.y;}else if(Math.hypot(s.lx-idlePost.x,s.ly-idlePost.y)>.6){const mv=C.reserveStep({x:s.lx,y:s.ly},idlePost,18,dt);s.lx=mv.x;s.ly=mv.y;}s.cd-=dt;s.recoil=Math.max(0,s.recoil-dt);if(s.action!=='idle'){s.timer-=dt;if(s.timer<=0){if(s.action==='aim'){const from=worldLocal(state.player,s.lx,s.ly),t=nearestPlayerTarget(from),range=LIGHT_RANGE[s.kind]||700;if(t&&Math.hypot(t.x-from.x,t.y-from.y)<range&&!blockedLight(from,t)){s.facing=Math.atan2(t.y-from.y,t.x-from.x);spawnLight(s.kind,from,{x:t.x,y:t.y,z:t.z||30},false,{target:t,shooter:s});s.action='fire';s.timer=s.kind==='bow'?.14:.16;s.recoil=s.kind==='musket'?.16:0;}else{s.action='idle';s.cd=.2;}}else{s.action='idle';s.cd=s.kind==='bow'?rand(.85,1.3):rand(1.75,2.55);}}continue;}if(s.cd<=0){const from=worldLocal(state.player,s.lx,s.ly),near=nearestPlayerTarget(from),range=LIGHT_RANGE[s.kind]||700;if(near&&Math.hypot(near.x-from.x,near.y-from.y)<range){const localThreat=state.boarders.some(b=>!b.dead&&b.state==='deck'&&Math.hypot(b.lx-s.lx,b.ly-s.ly)<30);if(localThreat){s.cd=.55;continue;}s.action='aim';s.timer=s.kind==='bow'?.25:.31;}else s.cd=.22;}}
}
function blockedLight(from,to){for(const e of state.enemies){if(e.removed||e.sinking)continue;const l1=localOf(e,from.x,from.y),l2=localOf(e,to.x,to.y);if(C.segmentPolygonHit(l1.x,l1.y,l2.x,l2.y,HULL)!==null){const targetOnShip=Math.hypot(to.x-e.x,to.y-e.y)<190;if(!targetOnShip)return true;}}return false;}
function spawnLight(kind,from,to,enemy,meta){const speed=kind==='musket'?780:330,dist=Math.hypot(to.x-from.x,to.y-from.y),life=clamp(dist/speed,.08,2),arc=kind==='bow'?18:2;state.lightShots.push({kind,x:from.x,y:from.y,vx:(to.x-from.x)/life,vy:(to.y-from.y)/life,age:0,life,maxLife:life,startZ:36,targetZ:to.z||30,arc,enemy,meta});state.metrics.lightFired++;state.metrics.maxProjectiles=Math.max(state.metrics.maxProjectiles,state.lightShots.length+state.shots.length);if(kind==='musket'){burst(from.x,from.y,'#ffd37b',3,18,'fire',36);tone(enemy?205:260,.045,.018);}else tone(420,.025,.009);}
function lightZ(b){const t=clamp(b.age/b.maxLife,0,1);return b.startZ+(b.targetZ-b.startZ)*t+Math.sin(Math.PI*t)*b.arc;}
function updateLightShots(dt){const keep=[];for(const b of state.lightShots){const ox=b.x,oy=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.age+=dt;b.life-=dt;let hit=false;const z=lightZ(b);
  if(b.enemy){const units=[...state.player.shooters,...state.player.defenders].filter(u=>u.alive&&!u.down);for(const u of units){const p=worldLocal(state.player,u.lx,u.ly);const t=C.segmentCircleFirst(ox,oy,b.x,b.y,p.x,p.y,9);if(t!==null&&z>18){damagePlayerUnit(u,b.kind==='musket'?10:3);b.x=ox+(b.x-ox)*t;b.y=oy+(b.y-oy)*t;hit=true;break;}}
  }else{for(const u of state.boarders){if(u.dead||!(u.state==='crossing'||u.state==='deck'))continue;const t=C.segmentCircleFirst(ox,oy,b.x,b.y,u.x,u.y,9);if(t!==null&&z>14){damageBoarder(u,b.kind==='musket'?10:3,b.kind,b.x,b.y);hit=true;break;}}if(!hit&&b.meta?.target?.remote){const t=b.meta.target;if(t.crew?.alive&&Math.hypot(b.x-t.x,b.y-t.y)<14){t.crew.hp-=b.kind==='musket'?10:3;if(t.crew.hp<=0)t.crew.alive=false;floatText(t.x,t.y,b.kind==='musket'?10:3,b.kind==='musket'?'#f4c46c':'#e8edcf',b.kind==='musket'?12:10,'remote'+t.crew.id);hit=true;}}}
  if(hit){state.metrics.lightHits++;burst(b.x,b.y,b.kind==='musket'?'#e7c58d':'#dce8ce',2,12,'spark',z);continue;}if(b.life<=0){splash(b.x,b.y);continue;}keep.push(b);}state.lightShots=keep;}
function damagePlayerUnit(u,amt){if(!u.alive||u.down)return;u.hp=Math.max(0,u.hp-amt);floatText(...Object.values(worldLocal(state.player,u.lx,u.ly)),amt,'#ffaaa0',10,'p'+u.id);if(u.hp<=0){u.down=true;u.alive=false;u.action='down';floatText(...Object.values(worldLocal(state.player,u.lx,u.ly)),'倒地','#ffb7ac',13);}}
function damageBoarder(u,amt,kind,x,y){if(u.dead)return;let real=amt;if(u.kind==='shield'){const rel=C.wrap(Math.atan2(y-u.y,x-u.x)-u.facing);real*=C.shieldMultiplier(rel);}real=Math.max(1,Math.round(real));u.hp=Math.max(0,u.hp-real);u.hitFlash=.12;u.prep=0;floatText(u.x,u.y,real,kind==='musket'?'#f4c46c':'#edf1d6',kind==='musket'?12:10,'b'+u.id);if(u.hp<=0){u.dead=true;u.state='dead';state.metrics.boardersKilled++;floatText(u.x,u.y,'击倒','#ffe1a0',12);}}
function updateBoarders(dt){for(const u of state.boarders){u.hitFlash=Math.max(0,u.hitFlash-dt);if(u.dead){u.z=Math.max(0,u.z-dt*12);continue;}const ship=state.enemies.find(s=>s.id===u.shipId),conn=ship?.connections.find(c=>c.id===u.connectionId);if(u.state==='enemyDeck'){if(!ship||!conn||conn.broken||ship.sinking){u.dead=true;u.fall=true;continue;}const a=connectionWorld(ship,conn,false),b=connectionWorld(ship,conn,true);u.x+=(a.x-u.x)*Math.min(1,dt*3);u.y+=(a.y-u.y)*Math.min(1,dt*3);if(Math.hypot(u.x-a.x,u.y-a.y)<8){u.state='crossing';u.progress=0;}}
 else if(u.state==='crossing'){if(!conn||conn.broken){if(ship&&!ship.sinking&&u.progress<.4){u.state='retreating';u.progress=0;}else{u.state='falling';u.fall=true;}continue;}u.progress=C.boardingAdvance(u.progress,dt,u.kind==='shield'?1.5:1.15);const a=connectionWorld(ship,conn,false),b=connectionWorld(ship,conn,true);u.x=a.x+(b.x-a.x)*u.progress;u.y=a.y+(b.y-a.y)*u.progress;u.z=30+Math.sin(Math.PI*u.progress)*8;if(u.progress>=1){u.state='deck';const l=localOf(state.player,u.x,u.y);u.lx=l.x;u.ly=l.y;state.metrics.boarded++;}}
 else if(u.state==='retreating'){if(!ship){u.dead=true;continue;}const back=connectionWorld(ship,conn||{offset:0},false),dx=back.x-u.x,dy=back.y-u.y,d=Math.hypot(dx,dy),v=115;if(d<8){u.dead=true;u.state='retreated';}else{u.x+=dx/(d||1)*v*dt;u.y+=dy/(d||1)*v*dt;u.z=28;}}
 else if(u.state==='falling'){u.z=Math.max(0,u.z-85*dt);u.x+=(ship?Math.sign(u.x-ship.x):1)*18*dt;if(u.z<=0){splash(u.x,u.y);u.dead=true;}}
 else if(u.state==='deck'){updateDeckEnemy(u,dt);}}
 state.boarders=state.boarders.filter(u=>!u.dead||u.z>1);}
function nearestDefender(u){
 let best=null,bd=Infinity;
 for(const d of state.player.defenders){if(!d.alive||d.down)continue;const dx=d.lx-u.lx,dy=d.ly-u.ly,dd=dx*dx+dy*dy;if(dd<bd){bd=dd;best=d;}}
 return best;
}
const DECK_OBSTACLES=[{x:-8,y:0,r:16},{x:-58,y:20,r:13},{x:55,y:-8,r:12}];
function deckNavTarget(u,goal){for(const o of DECK_OBSTACLES){const t=C.segmentCircleFirst(u.lx,u.ly,goal.x,goal.y,o.x,o.y,o.r+5);if(t!==null&&Math.hypot(u.lx-o.x,u.ly-o.y)>o.r+7){const side=u.ly<=o.y?-1:1;return{x:o.x+18,y:o.y+side*(o.r+12)};}}return goal;}
function updateDeckEnemy(u,dt){u.cd=Math.max(0,u.cd-dt);const def=nearestDefender(u);let goal;if(u.kind==='breaker'){const side=u.ly<0?'upper':'lower',facility=state.player.gunHp[side]>0?(side==='upper'?DECK.upperGun:DECK.lowerGun):DECK.cabin;u.targetFacility=state.player.gunHp[side]>0?side+'Gun':'cabin';goal=facility;}else goal=DECK.center;
 if(def&&Math.hypot(def.lx-u.lx,def.ly-u.ly)<30){goal={x:def.lx,y:def.ly};if(u.cd<=0){meleeEnemyAttack(u,def);u.cd=u.kind==='shield'?1.15:.86;}u.prep=0;}else if(u.kind==='breaker'&&Math.hypot(goal.x-u.lx,goal.y-u.ly)<18){u.prep+=dt;if(u.prep>1.65){u.prep=0;damageFacility(u);}}else{u.prep=0;const nav=deckNavTarget(u,goal),step=C.reserveStep({x:u.lx,y:u.ly},nav,u.kind==='shield'?28:u.kind==='breaker'?38:42,dt);u.lx=step.x;u.ly=step.y;const w=worldLocal(state.player,u.lx,u.ly);u.x=w.x;u.y=w.y;u.facing=Math.atan2(nav.y-u.ly,nav.x-u.lx);}}
function meleeEnemyAttack(u,d){d.hp=Math.max(0,d.hp-(u.kind==='shield'?9:12));d.action='hit';d.timer=.16;floatText(...Object.values(worldLocal(state.player,d.lx,d.ly)),u.kind==='shield'?9:12,'#ff9b8e',11,'md'+d.id);if(d.hp<=0){d.alive=false;d.down=true;d.action='down';}}
function damageFacility(u){const side=u.ly<0?'upper':'lower';if(state.player.gunHp[side]>0){state.player.gunHp[side]=Math.max(0,state.player.gunHp[side]-34);floatText(...Object.values(worldLocal(state.player,side==='upper'?44:44,side==='upper'?-46:46)),34,'#ff9b69',15,'fac'+side);toast('破坏兵正在破坏'+(side==='upper'?'上':'下')+'舷炮位！',1.3);}else{state.player.hp=Math.max(0,state.player.hp-42);state.metrics.damageTaken+=42;floatText(...Object.values(worldLocal(state.player,DECK.cabin.x,DECK.cabin.y)),42,'#ff8e72',16,'cabin');toast('船舱入口遭到破坏！',1.2);}}
function defenderPost(d){
 const off=C.crewMotionOffset(d.motionId,state.time,'melee');
 if(!d.reserve)return{x:d.homeLx+off.x*.32,y:d.homeLy+off.y*.32};
 const idx=Math.max(0,d.motionId-40),col=idx%5,row=Math.floor(idx/5),base=DEF_ZONES[d.targetZone]||DEF_ZONES.center;
 const sx=(col-2)*11,sy=(row-1.5)*8;
 return{x:base.x+sx+off.x*.2,y:clamp(base.y+sy+off.y*.2,-51,51)};
}
function updateDefenders(dt){for(const d of state.player.defenders){if(d.down){d.rescue+=dt;if(d.rescue>8&&safeAround(d)){d.down=false;d.alive=true;d.hp=Math.max(28,d.maxHp*.42);d.rescue=0;floatText(...Object.values(worldLocal(state.player,d.lx,d.ly)),'救起','#9fe4b7',12);}continue;}if(!d.alive)continue;d.cd=Math.max(0,d.cd-dt);if(d.action==='hit'||d.action==='attack'){d.timer-=dt;if(d.timer<=0)d.action='idle';}
  const targetPos=defenderPost(d);let close=null,closeD=Infinity;for(const e of state.boarders){if(e.dead||e.state!=='deck')continue;const dd=Math.hypot(e.lx-d.lx,e.ly-d.ly);if(dd<closeD){closeD=dd;close=e;}}
  let u=closeD<31?close:null;
  if(!u&&state.targetBoarderId){const manual=state.boarders.find(e=>e.id===state.targetBoarderId&&!e.dead&&e.state==='deck')||null;if(manual&&Math.hypot(manual.lx-d.lx,manual.ly-d.ly)<48)u=manual;}
  if(!u&&closeD<48)u=close;
  if(u&&Math.hypot(u.lx-d.lx,u.ly-d.ly)<29){d.facing=Math.atan2(u.ly-d.ly,u.lx-d.lx);if(d.cd<=0){u.hp=Math.max(0,u.hp-16);u.prep=0;d.cd=.68;d.action='attack';d.timer=.18;floatText(u.x,u.y,16,'#dff0cf',10,'melee'+u.id);if(u.hp<=0){u.dead=true;u.state='dead';state.metrics.boardersKilled++;}}}
  else{const mv=C.reserveStep({x:d.lx,y:d.ly},targetPos,d.reserve?52:18,dt);d.lx=mv.x;d.ly=mv.y;}
 }
}
function safeAround(d){return !state.boarders.some(u=>!u.dead&&u.state==='deck'&&Math.hypot(u.lx-d.lx,u.ly-d.ly)<45);}
function updateConnections(dt){state.openEntrances=openCount();for(const s of state.enemies){for(const c of s.connections){if(c.broken)continue;if(c.hp<=0){breakConnection(s,c);}}}}
function breakConnection(ship,conn){if(conn.broken)return;conn.broken=true;conn.open=false;conn.phase='broken';state.metrics.connectionsBroken++;burst(...Object.values(connectionWorld(ship,conn,true)),'#a97949',16,85,'wood',18);floatText(...Object.values(connectionWorld(ship,conn,true)),'连接断裂','#ffcf8f',15);toast('登船连接被摧毁 · 增援中断',1.6);}
function fireVolley(){if(state.paused||state.end||state.volley>0)return false;const s=state.enemies.find(e=>e.id===state.targetShipId&&!e.removed&&!e.sinking);if(!s){toast('先点击选择海上敌船');return false;}const dx=s.x-PLAYER_X,dy=s.y-PLAYER_Y,side=C.broadsideSide(0,dx,dy,720,90,70);if(!side){toast('目标不在有效侧舷射界');return false;}if(state.player.gunHp[side]<=0){toast((side==='upper'?'上':'下')+'舷炮位已失效');return false;}state.volley=VOLLEY_RELOAD;const gunCount=state.player.gunHp[side]>75?4:2;const pred=C.predictIntercept({x:PLAYER_X,y:PLAYER_Y,vx:AUTO_SPEED,vy:0},{x:s.x,y:s.y,vx:0,vy:0},420,1.8);for(let i=0;i<gunCount;i++){state.cannonQueue.push({due:state.time+i*.13,side,shipId:s.id,aim:{x:pred.x+rand(-14,14),y:pred.y+rand(-14,14)},damage:76,index:i});}state.metrics.cannonFired+=gunCount;state.player.recoil[side]=.25;toast('重炮齐射 · '+gunCount+'门依次开火',1.2);return true;}
function updateCannonQueue(){const keep=[];for(const q of state.cannonQueue){if(q.due>state.time){keep.push(q);continue;}if(state.player.gunHp[q.side]<=0)continue;const s=state.enemies.find(e=>e.id===q.shipId&&!e.removed&&!e.sinking);if(!s)continue;const source=worldLocal(state.player,30+(q.index%2)*42,q.side==='upper'?-60:60),dx=q.aim.x-source.x,dy=q.aim.y-source.y,d=Math.hypot(dx,dy),life=d/420;state.shots.push({x:source.x,y:source.y,vx:dx/life,vy:dy/life,age:0,life,maxLife:life,startZ:22,targetZ:20,arc:25,damage:q.damage,shipId:q.shipId,side:q.side});burst(source.x,source.y,'#ffd078',8,65,'fire',24);burst(source.x,source.y,'#eef1ec',8,45,'smoke',25);tone(72,.18,.08);state.shake=1.8;}state.cannonQueue=keep;}
function cannonZ(b){const t=clamp(b.age/b.maxLife,0,1);return b.startZ+(b.targetZ-b.startZ)*t+Math.sin(Math.PI*t)*b.arc;}
function updateCannonShots(dt){const keep=[];for(const b of state.shots){const ox=b.x,oy=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.age+=dt;b.life-=dt;let hit=null;for(const e of state.enemies){if(e.removed||e.sinking)continue;const a=localOf(e,ox,oy),c=localOf(e,b.x,b.y),t=C.segmentPolygonHit(a.x,a.y,c.x,c.y,HULL);if(t!==null&&(hit===null||t<hit.t))hit={e,t};}if(hit&&cannonZ(b)>3){const x=ox+(b.x-ox)*hit.t,y=oy+(b.y-oy)*hit.t;heavyHit(hit.e,b,x,y);continue;}if(b.life<=0){splash(b.x,b.y);continue;}keep.push(b);}state.shots=keep;}
function heavyHit(ship,b,x,y){state.metrics.cannonHits++;let didConnection=false;const active=ship.connections.filter(c=>!c.broken&&(c.open||c.phase==='building'));if(active.length&&ship.type!=='skiff'){const c=active.sort((a,b)=>b.progress-a.progress)[0];c.hp=Math.max(0,c.hp-b.damage);floatText(x,y,Math.min(b.damage,Math.round(c.hp+b.damage)),'#ffb45e',18,'conn'+c.id);if(c.hp<=0)breakConnection(ship,c);didConnection=true;}if(!didConnection){const actual=Math.min(ship.hp,b.damage);ship.hp-=actual;floatText(x,y,actual,'#ffad50',19,'ship'+ship.id);if(ship.type==='skiff'&&ship.hp<=0)toast('运兵艇被重炮击毁 · 增援被截断',1.5);}burst(x,y,'#d59a5b',18,125,'wood',22);if(ship.hp<=0)startSink(ship);}
function startSink(ship){if(ship.sinking)return;ship.sinking=true;ship.phase='sinking';ship.sinkTimer=0;for(const c of ship.connections)if(!c.broken)breakConnection(ship,c);burst(ship.x,ship.y,'#bc7d49',28,135,'wood',26);splash(ship.x,ship.y);}
function repair(){if(state.paused||state.end||state.repair>0||state.repairUses<=0)return;state.repairUses--;state.repair=18;state.player.hp=Math.min(state.player.maxHp,state.player.hp+85);state.player.water=Math.max(0,state.player.water-22);state.player.gunHp.upper=Math.min(state.player.gunMax,state.player.gunHp.upper+36);state.player.gunHp.lower=Math.min(state.player.gunMax,state.player.gunHp.lower+36);toast('应急维修 · 修复船体并抢修炮位',1.5);}
function updateFx(dt){for(const f of state.fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.z=Math.max(0,f.z+f.vz*dt);f.vz-=f.type==='water'||f.type==='wood'?145*dt:34*dt;f.life-=dt;if(f.type==='wood')f.rot+=f.vr*dt;}state.fx=state.fx.filter(f=>f.life>0);for(const t of state.texts){t.y-=20*dt;t.life-=dt;}state.texts=state.texts.filter(t=>t.life>0);state.metrics.maxFx=Math.max(state.metrics.maxFx,state.fx.length);state.metrics.maxTexts=Math.max(state.metrics.maxTexts,state.texts.length);}
function update(dt){if(!state||state.paused||state.end)return;state.time+=dt;state.scroll+=AUTO_SPEED*dt;state.toast=Math.max(0,state.toast-dt);state.shake=Math.max(0,state.shake-dt*14);state.repair=Math.max(0,state.repair-dt);if(state.volley>0)state.volley=Math.max(0,state.volley-dt);processWaves();for(const e of state.enemies)updateEnemyShip(e,dt);updateConnections(dt);updateShooters(dt);updateDefenders(dt);updateBoarders(dt);updateCannonQueue();updateCannonShots(dt);updateLightShots(dt);updateFx(dt);state.player.recoil.upper=Math.max(0,state.player.recoil.upper-dt);state.player.recoil.lower=Math.max(0,state.player.recoil.lower-dt);state.player.water=clamp(state.player.water+state.player.breaches.length*.005*dt,0,100);if(state.player.hp<=0){state.end='lose';dialogEnd(false);}const allWaves=state.waveIndex>=WAVES.length&&state.pending.length===0,clear=state.enemies.every(e=>e.removed||e.sinking)&&state.boarders.every(b=>b.dead);if(allWaves&&clear&&!state.end){state.settle+=dt;if(state.settle>2){state.end='win';dialogEnd(true);}}else state.settle=0;state.metrics.maxUnits=Math.max(state.metrics.maxUnits,state.boarders.length+state.enemies.length+state.player.shooters.length+state.player.defenders.length);}
function dialogEnd(win){state.lastWin=!!win;$('overlay').classList.remove('hidden');$('modalEyebrow').textContent=win?'DECK SECURED':'SHIP LOST';$('modalTitle').textContent=win?'甲板守住了':'旗舰失守';$('modalText').textContent=win?'主力登船队已被击退。可以立即重玩继续挑战。':'船体耐久归零。调整预备队位置和重炮保留时机再试。';$('instructions').classList.add('hidden');$('resume').textContent='继续挑战';}
function pause(){if(state.end)return;state.paused=!state.paused;$('pause').textContent=state.paused?'▶':'Ⅱ';$('overlay').classList.toggle('hidden',!state.paused);if(state.paused){$('modalEyebrow').textContent='PAUSED';$('modalTitle').textContent='战斗暂停';$('modalText').textContent='甲板战和所有弹丸已暂停。';$('instructions').classList.add('hidden');$('resume').textContent='继续战斗 →';}}
function pick(clientX,clientY){const wx=clientX/scale+state.cameraX,wy=clientY/(scale*YCOMP)+state.cameraY;let bu=null,bd=42;for(const b of state.boarders){if(b.dead||!(b.state==='deck'||b.state==='crossing'))continue;const p=project(b.x,b.y,b.z),d=Math.hypot(clientX-p.x,clientY-p.y);if(d<bd){bd=d;bu=b;}}if(bu){state.targetBoarderId=bu.id;toast('甲板优先集火 · '+unitName(bu.kind),1.2);return;}let pickShip=null,best=210;for(const e of state.enemies){if(e.removed||e.sinking)continue;const d=Math.hypot(wx-e.x,wy-e.y);if(d<best){best=d;pickShip=e;}}if(pickShip){state.targetShipId=pickShip.id;state.targetBoarderId=null;toast('舰炮目标 · '+pickShip.cfg.name,1.2);}}
function unitName(k){return k==='shield'?'盾兵':k==='breaker'?'破坏兵':'突击兵';}
function drawSea(){const g=ctx.createLinearGradient(0,50,0,height);g.addColorStop(0,'#0d819d');g.addColorStop(.55,'#0a748f');g.addColorStop(1,'#075d78');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);ctx.save();ctx.globalAlpha=.14;ctx.strokeStyle='#b9f6ff';ctx.lineWidth=1;const shift=(state.scroll*scale*.45)%76;for(let y=-40;y<height+50;y+=39){ctx.beginPath();for(let x=-100-shift;x<width+80;x+=55){const yy=y+Math.sin(x*.018+state.time*1.5+y*.02)*4;if(x<-80-shift)ctx.moveTo(x,yy);else ctx.lineTo(x,yy);}ctx.stroke();}ctx.restore();for(let i=0;i<8;i++){const x=((i*263-state.scroll*.32)%1900+1900)%1900-100,y=90+(i*137)%760;drawDistantRock(x,y,i);}}
function drawDistantRock(x,y,i){ctx.save();ctx.globalAlpha=.45;ctx.fillStyle=i%3?'#6e887f':'#b7c08c';ctx.beginPath();ctx.ellipse(x,y,18+(i%4)*5,7+(i%3)*2,0,0,TAU);ctx.fill();ctx.restore();}
function drawHull(ship,col='#8b542e',trim='#246ea6',size=1){ctx.save();const p=project(ship.x,ship.y,0);ctx.translate(p.x,p.y);ctx.rotate(ship.a);ctx.scale(scale*size,scale*YCOMP*size);ctx.fillStyle='#052b3b45';ctx.beginPath();ctx.ellipse(-5,20,155,48,0,0,TAU);ctx.fill();ctx.fillStyle=col;ctx.strokeStyle='#3f271a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-176,-52);ctx.lineTo(-128,-70);ctx.lineTo(80,-61);ctx.lineTo(185,0);ctx.lineTo(75,62);ctx.lineTo(-132,70);ctx.lineTo(-176,52);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#bc8348';ctx.beginPath();ctx.moveTo(-150,-45);ctx.lineTo(86,-51);ctx.lineTo(156,0);ctx.lineTo(83,51);ctx.lineTo(-150,43);ctx.closePath();ctx.fill();ctx.strokeStyle=trim;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-135,45);ctx.lineTo(100,48);ctx.stroke();ctx.fillStyle='#1f2426';for(let x=-100;x<100;x+=34){ctx.beginPath();ctx.arc(x,48,4,0,TAU);ctx.fill();}ctx.restore();}
function drawShip(ship){const enemy=ship.team==='enemy',size=enemy?(ship.cfg?.size||1):PLAYER_SCALE;drawHull(ship,enemy?'#713623':'#8b542e',enemy?'#a72d2b':'#246ea6',size);const p=project(ship.x,ship.y,0);ctx.save();ctx.translate(p.x,p.y);ctx.scale(size,size);const mast=project(ship.x-20,ship.y,82*size),base=project(ship.x-20,ship.y,18*size);ctx.strokeStyle='#5a3920';ctx.lineWidth=5*scale;ctx.beginPath();ctx.moveTo(base.x-p.x,base.y-p.y);ctx.lineTo(mast.x-p.x,mast.y-p.y);ctx.stroke();ctx.fillStyle='#eadbb4cc';ctx.strokeStyle='#8e764e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(mast.x-p.x-25*scale,mast.y-p.y+12*scale);ctx.lineTo(mast.x-p.x+25*scale,mast.y-p.y+12*scale);ctx.lineTo(mast.x-p.x+16*scale,mast.y-p.y+43*scale);ctx.lineTo(mast.x-p.x-17*scale,mast.y-p.y+40*scale);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();if(enemy)drawEnemyCrew(ship);if(ship.sinking){ctx.save();ctx.globalAlpha=.35+ship.sink*.5;ctx.fillStyle='#07546b';const q=project(ship.x,ship.y,0);ctx.beginPath();ctx.ellipse(q.x,q.y+18*scale,170*scale*size,38*scale*size,0,0,TAU);ctx.fill();ctx.restore();}}
function drawEnemyCrew(ship){for(const c of ship.crew){const p=worldLocal(ship,c.lx,c.ly),q=project(p.x,p.y,31),sz=4.2*scale*(ship.cfg?.size||1);ctx.fillStyle=c.alive?'#c84d43':'#5b3b35';ctx.beginPath();ctx.arc(q.x,q.y,sz,0,TAU);ctx.fill();if(c.alive){const len=c.kind==='musket'?16:12,end=project(p.x+Math.cos(c.facing)*len,p.y+Math.sin(c.facing)*len,32);ctx.strokeStyle=c.kind==='musket'?'#2b3033':'#70442a';ctx.lineWidth=(c.kind==='musket'?2.2:1.5)*scale;ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(end.x,end.y);ctx.stroke();if(c.action==='fire'&&c.kind==='musket'){ctx.fillStyle='#ffd27a';ctx.beginPath();ctx.arc(end.x,end.y,2.4*scale,0,TAU);ctx.fill();}}}}
function drawDeckObstacles(){for(const o of DECK_OBSTACLES){const p=shipPt(state.player,o.x,o.y,23);ctx.save();ctx.fillStyle='#77502f';ctx.strokeStyle='#4a301e';ctx.lineWidth=2*scale;ctx.fillRect(p.x-o.r*.55*scale,p.y-o.r*.35*scale,o.r*1.1*scale,o.r*.7*scale);ctx.strokeRect(p.x-o.r*.55*scale,p.y-o.r*.35*scale,o.r*1.1*scale,o.r*.7*scale);ctx.restore();}}
function drawReloadCrew(){if(state.volley<=0)return;const phase=1-state.volley/VOLLEY_RELOAD;for(const side of['upper','lower']){if(state.player.gunHp[side]<=0)continue;const y=side==='upper'?-45:45;for(let i=0;i<2;i++){const x=18+i*45,p=shipPt(state.player,x,y,33+Math.sin(state.time*7+i)*2);ctx.save();ctx.fillStyle='#2f73c9';ctx.beginPath();ctx.arc(p.x,p.y,4.2*scale,0,TAU);ctx.fill();ctx.strokeStyle='#d5b97e';ctx.lineWidth=2*scale;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+(5+phase*5)*scale,p.y-5*scale);ctx.stroke();ctx.restore();}}}
function drawPlayerCrew(){drawDeckObstacles();for(const u of [...state.player.shooters,...state.player.defenders])drawDeckUnit(u);drawReloadCrew();}
function drawDeckUnit(u){const base=shipPt(state.player,u.lx,u.ly,20),body=shipPt(state.player,u.lx,u.ly,30),head=shipPt(state.player,u.lx,u.ly,39);ctx.save();if(u.down||!u.alive){ctx.strokeStyle='#284b70';ctx.lineWidth=4*scale;ctx.beginPath();ctx.moveTo(base.x,base.y);ctx.lineTo(base.x+12*scale,base.y+3*scale);ctx.stroke();ctx.restore();return;}ctx.strokeStyle='#174b83';ctx.lineWidth=4*scale;ctx.beginPath();ctx.moveTo(base.x,base.y);ctx.lineTo(body.x,body.y);ctx.stroke();ctx.fillStyle=u.role==='melee'?'#3c82ca':'#2f73c9';ctx.beginPath();ctx.arc(body.x,body.y,5*scale,0,TAU);ctx.fill();ctx.fillStyle='#dfb486';ctx.beginPath();ctx.arc(head.x,head.y,4*scale,0,TAU);ctx.fill();const dir=u.facing||0,end=project(worldLocal(state.player,u.lx,u.ly).x+Math.cos(dir)*(u.kind==='musket'?21:16),worldLocal(state.player,u.lx,u.ly).y+Math.sin(dir)*(u.kind==='musket'?21:16),34);ctx.strokeStyle=u.role==='melee'?'#c7c3b0':u.kind==='musket'?'#2b3033':'#744827';ctx.lineWidth=(u.role==='melee'?3:u.kind==='musket'?3:2)*scale;ctx.beginPath();ctx.moveTo(body.x,body.y);ctx.lineTo(end.x,end.y);ctx.stroke();if(u.reserve){ctx.strokeStyle='#ffe09b';ctx.lineWidth=1;ctx.beginPath();ctx.arc(base.x,base.y+4*scale,8*scale,0,TAU);ctx.stroke();}ctx.restore();}
function drawBoarder(u){if(u.dead&&u.z<=1)return;const p=project(u.x,u.y,u.z||28);ctx.save();ctx.fillStyle=u.kind==='shield'?'#a52f31':u.kind==='breaker'?'#d56b32':'#c64940';ctx.beginPath();ctx.arc(p.x,p.y,5.5*scale,0,TAU);ctx.fill();ctx.fillStyle='#e0a77d';ctx.beginPath();ctx.arc(p.x,p.y-9*scale,4*scale,0,TAU);ctx.fill();if(u.kind==='shield'){ctx.fillStyle='#6b2024';ctx.fillRect(p.x-8*scale,p.y-3*scale,5*scale,12*scale);}if(u.kind==='breaker'&&u.prep>0){ctx.strokeStyle='#ffdf86';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,11*scale,-Math.PI/2,-Math.PI/2+TAU*clamp(u.prep/1.65,0,1));ctx.stroke();}if(u.id===state.targetBoarderId){ctx.strokeStyle='#ffe08a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,13*scale,0,TAU);ctx.stroke();}ctx.restore();}
function drawConnections(){for(const ship of state.enemies){for(const c of ship.connections){if(c.phase==='idle'||c.broken&&c.progress<=0)continue;const a=connectionWorld(ship,c,false),b=connectionWorld(ship,c,true),pa=project(a.x,a.y,20),pb=project(b.x,b.y,20);ctx.save();ctx.lineWidth=6*scale;ctx.strokeStyle=c.broken?'#6b4a34':'#b48a52';ctx.setLineDash(c.broken?[7*scale,8*scale]:[]);ctx.beginPath();ctx.moveTo(pa.x,pa.y);const t=c.progress;ctx.lineTo(pa.x+(pb.x-pa.x)*t,pa.y+(pb.y-pa.y)*t);ctx.stroke();ctx.setLineDash([]);if(c.open&&!c.broken){ctx.strokeStyle='#e2c68a';ctx.lineWidth=1;ctx.strokeRect(pb.x-12*scale,pb.y-8*scale,24*scale,16*scale);}if(!c.broken&&(c.open||c.phase==='building')){ctx.fillStyle='#102833cc';ctx.fillRect(pb.x-18*scale,pb.y+11*scale,36*scale,4*scale);ctx.fillStyle='#e4b56d';ctx.fillRect(pb.x-18*scale,pb.y+11*scale,36*scale*clamp(c.hp/c.maxHp,0,1),4*scale);}ctx.restore();}}
}
function drawLight(b){const p=project(b.x,b.y,lightZ(b)),a=Math.atan2(b.vy*YCOMP,b.vx);ctx.save();if(b.kind==='arrow'){ctx.strokeStyle=b.enemy?'#ffd0b5':'#edf2d0';ctx.lineWidth=1.4*scale;ctx.beginPath();ctx.moveTo(p.x-Math.cos(a)*8*scale,p.y-Math.sin(a)*8*scale);ctx.lineTo(p.x+Math.cos(a)*5*scale,p.y+Math.sin(a)*5*scale);ctx.stroke();}else{ctx.strokeStyle=b.enemy?'#ffb58a':'#ffe2a0';ctx.lineWidth=2*scale;ctx.beginPath();ctx.moveTo(p.x-Math.cos(a)*13*scale,p.y-Math.sin(a)*13*scale);ctx.lineTo(p.x,p.y);ctx.stroke();}ctx.restore();}
function drawCannon(b){const base=project(b.x,b.y,0),p=project(b.x,b.y,cannonZ(b));ctx.fillStyle='#11191d77';ctx.beginPath();ctx.ellipse(base.x,base.y,6*scale,3*scale,0,0,TAU);ctx.fill();ctx.fillStyle='#24262a';ctx.beginPath();ctx.arc(p.x,p.y,6*scale,0,TAU);ctx.fill();}
function drawFx(f){const p=project(f.x,f.y,f.z);ctx.save();ctx.globalAlpha=clamp(f.life/f.max,0,1);ctx.fillStyle=f.color;if(f.type==='wood'){ctx.translate(p.x,p.y);ctx.rotate(f.rot);ctx.fillRect(-5*scale,-2*scale,10*scale,4*scale);}else{ctx.beginPath();ctx.arc(p.x,p.y,f.r*scale,0,TAU);ctx.fill();}ctx.restore();}
function drawText(t){const p=project(t.x,t.y,45);ctx.save();ctx.globalAlpha=clamp(t.life,0,1);ctx.fillStyle=t.color;ctx.font=`700 ${t.size*scale}px Microsoft YaHei, sans-serif`;ctx.textAlign='center';ctx.fillText(t.text,p.x,p.y);ctx.restore();}
function drawThreatLabels(){for(const s of state.enemies){if(s.removed||s.sinking)continue;const p=project(s.x,s.y,105*(s.cfg.size||1));ctx.save();ctx.textAlign='center';ctx.font=`700 ${11*scale}px Microsoft YaHei`;ctx.fillStyle='#ffd3bd';ctx.fillText(`${s.cfg.name} · 待登船 ${s.remaining}`,p.x,p.y);ctx.fillStyle='#071e29cc';ctx.fillRect(p.x-52*scale,p.y+7*scale,104*scale,6*scale);ctx.fillStyle='#d95443';ctx.fillRect(p.x-52*scale,p.y+7*scale,104*scale*clamp(s.hp/s.maxHp,0,1),6*scale);if(s.id===state.targetShipId){ctx.strokeStyle='#ffe08a';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(project(s.x,s.y).x,project(s.x,s.y).y,185*scale*(s.cfg.size||1),65*scale*(s.cfg.size||1),0,0,TAU);ctx.stroke();}ctx.restore();}}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);ctx.save();ctx.translate(rand(-state.shake,state.shake),rand(-state.shake,state.shake));drawSea();for(const s of [...state.enemies,state.player].filter(s=>!s.removed).sort((a,b)=>project(a.x,a.y).y-project(b.x,b.y).y))drawShip(s);drawConnections();drawPlayerCrew();for(const b of state.boarders)drawBoarder(b);for(const b of state.lightShots)drawLight(b);for(const b of state.shots)drawCannon(b);for(const f of state.fx)drawFx(f);for(const t of state.texts)drawText(t);drawThreatLabels();ctx.restore();drawMini();}
function drawMini(){mini.clearRect(0,0,180,122);mini.fillStyle='#073946';mini.fillRect(0,0,180,122);mini.fillStyle='#71d8df';mini.beginPath();mini.arc(50,61,5,0,TAU);mini.fill();for(const e of state.enemies){if(e.removed)continue;const x=50+clamp((e.x-PLAYER_X)/8,-35,115),y=61+clamp((e.y-PLAYER_Y)/7,-50,50);mini.fillStyle='#fa876c';mini.beginPath();mini.arc(x,y,e.type==='large'?5:3.5,0,TAU);mini.fill();}mini.fillStyle='#e7d69a';mini.font='9px sans-serif';mini.fillText(`甲板敌人 ${deckEnemyCount()}`,5,116);}
function updateHud(){if(!state)return;const p=state.player;$('hpText').textContent=Math.ceil(p.hp)+' / '+p.maxHp;$('hpBar').style.width=clamp(p.hp/p.maxHp*100,0,100)+'%';$('waterText').textContent=Math.round(p.water)+'%';$('waterBar').style.width=Math.round(p.water)+'%';$('repairUses').textContent=state.repairUses;$('kills').textContent=state.metrics.shipsSunk;$('enemyTotal').textContent=SWARM_TOTAL;const liveEnemy=$('enemyCountLive');if(liveEnemy)liveEnemy.textContent=activeThreats();$('clock').textContent=String(Math.floor(state.time/60)).padStart(2,'0')+':'+String(Math.floor(state.time%60)).padStart(2,'0');$('speedText').textContent='自动航行 8 kn';const load=state.volley>0?1-state.volley/VOLLEY_RELOAD:1;$('volleyLoad').style.width=(clamp(load,0,1)*100)+'%';$('volleyCd').textContent=state.volley>0?`装填 ${state.volley.toFixed(1)}s`:'SPACE · 重炮就绪';$('repairCd').textContent=state.repairUses<=0?'R · 已用尽':state.repair>0?`${Math.ceil(state.repair)}s · 冷却`:`R · ${state.repairUses}次`;$('volley').disabled=state.volley>0||state.paused||!!state.end;$('repair').disabled=state.repair>0||state.repairUses<=0||state.paused||!!state.end;$('volley').classList.toggle('ready',state.volley<=0);$('toast').style.opacity=state.toast>0?'1':'0';const target=state.enemies.find(e=>e.id===state.targetShipId&&!e.removed);$('aimStatus').textContent=target?`舰炮目标：${target.cfg.name} · ${target.side==='upper'?'上舷':'下舷'}侧`:'点击敌船选择舰炮目标';const focus=state.boarders.find(b=>b.id===state.targetBoarderId&&!b.dead);$('targetStatus').textContent=focus?`甲板优先：${unitName(focus.kind)}`:`预备队：${state.reserveZone==='upper'?'上舷':state.reserveZone==='lower'?'下舷':'中央'} · 甲板敌人 ${deckEnemyCount()}`;$('missionText').textContent=`第 ${Math.min(state.waveIndex+1,WAVES.length)} / ${WAVES.length} 波 · 海上敌船 ${activeThreats()}/${MAX_ACTIVE_SHIPS} · 甲板敌人 ${deckEnemyCount()} · 登船口 ${openCount()}/${MAX_OPEN}`;if(debug)updateDebug();}
function updateDebug(){const s=state,m=s.metrics,connections=s.enemies.flatMap(e=>e.connections).map(c=>`${c.id}: ${c.phase} HP${Math.round(c.hp)} ${c.open?'OPEN':''}${c.broken?' BROKEN':''}`).join('\n');$('debugText').textContent=`模式: 持续航行·甲板守卫\n时间: ${s.time.toFixed(1)}s / 波次 ${s.waveIndex}/${WAVES.length}\n敌船: ${s.enemies.filter(e=>!e.removed).length}\n累计登船: ${m.boarded} / 甲板现存 ${deckEnemyCount()}\n开放入口: ${openCount()}/${MAX_OPEN}\n舰炮: ${m.cannonHits}/${m.cannonFired} 命中\n轻武器: ${m.lightHits}/${m.lightFired} 命中\n摧毁连接: ${m.connectionsBroken}\n击沉敌船: ${m.shipsSunk}\n船体受伤: ${m.damageTaken}\n上舷炮位: ${Math.round(s.player.gunHp.upper)}/${s.player.gunMax}\n下舷炮位: ${Math.round(s.player.gunHp.lower)}/${s.player.gunMax}\n对象峰值: 单位${m.maxUnits} / 弹丸${m.maxProjectiles} / 特效${m.maxFx} / 飘字${m.maxTexts}\n--- 入口 ---\n${connections}`;}
function toggleDebug(){debug=!debug;$('debugPanel').classList.toggle('hidden',!debug);if(debug)updateDebug();}
function runSelfTests(){const r=[],ok=(n,c)=>r.push({name:n,pass:!!c});const p=state.player;ok('默认甲板守卫模式',state.mode==='guard');ok('四弓两枪',p.shooters.filter(x=>x.kind==='bow').length===4&&p.shooters.filter(x=>x.kind==='musket').length===2);ok('上下舷固定守军各2',p.defenders.filter(x=>!x.reserve&&x.zone==='upper').length===2&&p.defenders.filter(x=>!x.reserve&&x.zone==='lower').length===2);ok('预备队2人',p.defenders.filter(x=>x.reserve).length===2);ok('全场最多两个入口',C.connectionOpenAllowed(2,2)===false);const step=C.reserveStep({x:0,y:0},{x:100,y:0},50,.5);ok('预备队非瞬移',step.x===25&&!step.arrived);const savedVolley=state.volley;state.volley=0;ok('重炮开局可用且12秒装填',state.volley===0&&VOLLEY_RELOAD===12);state.volley=savedVolley;const ship=makeEnemy('large','upper');ok('大船两个独立登船区',ship.connections.length===2&&ship.connections[0].hp>0&&ship.connections[1].hp>0);ship.connections[0].hp=0;breakConnection(ship,ship.connections[0]);ok('大船登船区可独立破坏',ship.connections[0].broken&&!ship.connections[1].broken&&ship.connections[1].hp===ship.connections[1].maxHp);const board=makeBoarder(ship,ship.connections[1],'assault',0);board.state='deck';state.boarders.push(board);startSink(ship);ok('运兵船沉没不删除已登船敌人',state.boarders.includes(board)&&!board.dead);state.boarders.pop();const breaker=makeBoarder(ship,ship.connections[1],'breaker',1);breaker.state='deck';breaker.lx=DECK.upperGun.x;breaker.ly=DECK.upperGun.y;let savedDef=p.defenders.map(d=>({alive:d.alive,down:d.down,hp:d.hp})),gun0=p.gunHp.upper;for(const d of p.defenders){d.alive=false;d.down=true;}for(let i=0;i<20;i++)updateDeckEnemy(breaker,.1);ok('破坏兵准备后能伤设施',p.gunHp.upper<gun0);breaker.prep=1;damageBoarder(breaker,3,'arrow',breaker.x,breaker.y);ok('破坏兵受击会打断准备',breaker.prep===0);p.gunHp.upper=gun0;p.defenders.forEach((d,i)=>Object.assign(d,savedDef[i]));return r;}
function frame(t){const dt=Math.min((t-last)/1000||.016,.04);last=t;update(dt);draw();updateHud();raf=requestAnimationFrame(frame);}
canvas.addEventListener('pointerdown',e=>{if(!state.paused&&!state.end)pick(e.clientX,e.clientY);});window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();fireVolley();}if(e.code==='Digit1')setReserveZone('upper');if(e.code==='Digit2')setReserveZone('center');if(e.code==='Digit3')setReserveZone('lower');if(e.code==='KeyR')repair();if(e.code==='KeyP'||e.code==='Escape')pause();if(e.code==='F2')toggleDebug();});
$('volley').onclick=fireVolley;$('repair').onclick=repair;$('pause').onclick=pause;$('help').onclick=()=>{state.paused=true;$('overlay').classList.remove('hidden');$('modalEyebrow').textContent='DECK GUARD';$('modalTitle').textContent='持续航行·甲板守卫';$('modalText').textContent='守甲板、调预备队、用重炮切断增援。';$('instructions').classList.remove('hidden');$('resume').textContent='继续战斗 →';};$('debug').onclick=toggleDebug;$('resume').onclick=()=>{if(state.end){resetGuard(state.lastWin?state.variant+1:state.variant);return;}state.paused=false;$('overlay').classList.add('hidden');$('pause').textContent='Ⅱ';};$('restart').onclick=()=>resetGuard(state.variant);$('layoutModal').onclick=()=>resetGuard(state.variant+1);$('retryScene').onclick=()=>resetGuard(state.variant);$('changeLayout').onclick=()=>resetGuard(state.variant+1);$('sound').onclick=()=>{sound=!sound;$('sound').style.color=sound?'#ffe19b':'';tone(260,.08,.03);};$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game').requestFullscreen();}catch{toast('当前浏览器不支持全屏');}};
resize();resetGuard(0);globalThis.NavalGuard={get state(){return state;},reset:resetGuard,step:update,fireVolley,setReserveZone,repair,pause,runSelfTests,render:draw,stop(){cancelAnimationFrame(raf);}};if(new URLSearchParams(location.search).has('selftest')){const results=runSelfTests(),pre=document.createElement('pre');pre.id='selftest';pre.textContent=results.map(r=>(r.pass?'PASS ':'FAIL ')+r.name).join('\n');document.body.appendChild(pre);document.body.dataset.selftest=results.every(r=>r.pass)?'pass':'fail';setTimeout(()=>cancelAnimationFrame(raf),60);}else raf=requestAnimationFrame(frame);
})();
