const fs=require('fs');
const assert=require('assert');
const path='js/v8/43_v101_chunk_damage.js';
assert(fs.existsSync(path),'V10.1 chunk damage module should exist');
const src=fs.readFileSync(path,'utf8');
const physics=fs.readFileSync('js/v8/43_v100_chunk_physics.js','utf8');
assert(src.includes('damageChunk'),'chunk module must expose damageChunk');
assert(src.includes('splitChunk'),'chunk module must expose splitChunk');
assert(src.includes('MAX_STRUCTURAL_CHUNKS'),'chunk count must stay bounded');
assert(src.includes('hitTestSegment'),'projectiles should be able to hit structural chunks in open water');
assert(src.includes('onShipCollision'),'V10.1 chunk damage must handle high-energy chunk-vs-ship contacts');
assert(src.includes('damageCell'),'chunk collision damage must reuse the physical grid damage chain');
assert(physics.includes('onShipCollision'),'V10 chunk collision solver must delegate impact damage to V10.1');
console.log('V10.1 chunk damage contract passed');
