'use strict';
const {assert,makeContext,makeState,loadV105Core}=require('./v10_5_test_helpers');
const ctx=makeContext(),st=makeState(ctx),Crew=loadV105Core(ctx);
Crew.prepareBattle(st);
assert.equal(st.player.crew.length,11);
assert.equal(st.player.crew.filter(c=>c.role==='captain').length,1);
assert.equal(st.player.crew.filter(c=>c.role==='gunner').length,4);
assert.equal(st.player.crew.filter(c=>c.role==='sailor').length,5);
assert.equal(st.player.crew.filter(c=>c.role==='helmsman').length,1);
assert.ok(st.player.crew.every(c=>c.ownerShipId==='player'&&c.currentShipId==='player'&&c.alive));
const first=st.player.crew[0];
Crew.prepareBattle(st);
assert.strictEqual(st.player.crew[0],first);
Crew.damageCrew(first,999,{kind:'cannon'});
Crew.prepareBattle(st);
assert.strictEqual(st.player.crew[0],first);
assert.equal(first.alive,false);
assert.equal(first.state,'dead');
const enemy=st.enemies[0];
assert.ok(enemy.crew.length>=5&&enemy.crew.length<=7);
assert.ok(enemy.crew.some(c=>c.combatClass==='swordsman'));
assert.ok(enemy.crew.some(c=>c.combatClass==='archer'));
assert.ok(enemy.crew.filter(c=>c.combatClass==='eliteCaptain').length<=1);
console.log('V10.5 crew roster: PASS');
