const assert=require('assert'),fs=require('fs'),vm=require('vm');
assert(fs.existsSync('js/v8/35_v100_fracture.js'),'V10 fracture module should exist');
const src=fs.readFileSync('js/v8/35_v100_fracture.js','utf8');
for(const token of ['V100Fracture','MAX_RADIUS=10','MAX_PROPAGATION_NODES=18','function propagate','crackDepth','crackDirX','crackDirY']) assert(src.includes(token),token);
const grid={CELL_WEIGHT:{hull:1,beam:2},damageCell(){return{hit:true,destroyed:false}}};
const ctx={globalThis:{V8ShipGrid:grid,V99Structure:{queueLocalSolve(){}}},console,Math};
vm.createContext(ctx);vm.runInContext(src,ctx);
const F=ctx.globalThis.V100Fracture;assert(F,'V100Fracture export');
const cell={gx:2,gy:2,type:'hull',alive:true,hp:20,maxHp:36,fracture:.2,fatigue:.1};
const ship={cellMap:{'2,2':cell},cells:[cell],gridWidth:5,gridHeight:5};
F.seedImpact(ship,cell,{vx:100,vy:0,power:120,grade:'heavy'});
assert(cell.crackDepth>0,'direct impact should deepen crack');
assert(Number.isFinite(cell.crackDirX)&&Number.isFinite(cell.crackDirY),'crack direction should exist');
assert((ship.__v100CrackRevision||0)>0,'crack revision should change');
const projectile=fs.readFileSync('js/v8/20_projectiles.js','utf8');
assert(projectile.includes('V100Fracture'),'direct impact must feed crack network');
const splash=fs.readFileSync('js/v8/32_v954_impact_explosion.js','utf8');
assert(splash.includes('V100Fracture'),'splash must feed crack network');
console.log('V10 fracture behavior passed');
