const fs=require('fs');
const assert=require('assert');
const path='js/v8/39_v101_compartment_water_visual.js';
assert(fs.existsSync(path),'V10.1 compartment water visual module should exist');
const src=fs.readFileSync(path,'utf8');
const comps=fs.readFileSync('js/v8/37_v99_compartments.js','utf8');
const sinking=fs.readFileSync('js/v8/40_v100_sinking.js','utf8');
assert(src.includes('__v99Compartments'),'water visual must use existing compartment water data');
assert(src.includes('__v101WaterVisual'),'water visual cache should be stored on ship');
assert(src.includes('revision'),'water visual should be cache/revision driven');
assert(src.includes('draw'),'water visual module should expose drawing behavior');
assert(comps.includes('FLOW_STEP'),'compartment transfer should use a bounded low-frequency step');
assert(comps.includes('__v101FlowAccumulator'),'ship should accumulate water transfer dt');
assert(sinking.includes('__v101ImmersionSeverity'),'low-side openings should record physical immersion severity');
console.log('V10.1 water visual contract passed');
