const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const ctx={console,Math,setTimeout,clearTimeout};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['js/v8/00_v8_base.js','js/v8/10_ship_grid.js','js/v8/20_projectiles.js','js/v8/30_battle.js']) vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const G=ctx.V8ShipGrid,B=ctx.V8Battle;
const state=B.newGame();
const ship=B.spawnEnemy(state,'gunship',{x:1000,y:500});
const powder=ship.cells.find(c=>c.type==='powder');assert(powder,'powder exists');
const near=ship.cells.filter(c=>c.alive&&c!==powder&&Math.hypot(c.gx-powder.gx,c.gy-powder.gy)<=2.01);
const before=new Map(near.map(c=>[c,c.hp]));
G.damageCell(ship,powder,999);
const chain={triggered:new Set()};
B.applyComponentDestroyed(state,ship,powder,G.cellCenterWorld(ship,powder),chain);
const changed=near.filter(c=>c.hp<before.get(c)||!c.alive);
assert(state.fx.some(f=>f.k==='powderBlast'),'powder blast fx');
assert(changed.length>=2,'powder blast damages multiple nearby cells');
assert(state.shake>=10,'powder blast uses strong shake');
assert(state.hitStop>0&&state.hitStop<=.075,'powder blast hit stop remains bounded under V8.4 critical feedback');
assert.strictEqual(chain.triggered.size,1,'same powder triggers once per chain');
B.applyComponentDestroyed(state,ship,powder,G.cellCenterWorld(ship,powder),chain);
assert.strictEqual(chain.triggered.size,1,'repeated handling cannot retrigger same powder');

const systems=B.spawnEnemy(state,'sloop',{x:1200,y:700});
B.recomputeShipSystems(systems);const base=systems.speed;
for(const c of systems.cells)if(c.type==='rudder')c.alive=false;
B.recomputeShipSystems(systems);assert(systems.speed<base,'destroyed rudder slows ship');
for(const c of systems.cells)if(c.type==='mast')c.alive=false;
B.recomputeShipSystems(systems);assert(systems.speed<=base*.55,'destroyed mast stacks speed loss');
for(const c of systems.cells)if(c.type==='cannon')c.alive=false;
B.recomputeShipSystems(systems);assert.strictEqual(systems.cannonsAlive,0,'destroyed cannons are counted');
console.log('V8.2 powder chain + systems compatibility tests passed');
