const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const ctx={console,Math,setTimeout,clearTimeout};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['js/v8/00_v8_base.js','js/v8/10_ship_grid.js','js/v8/20_projectiles.js','js/v8/30_battle.js','js/v8/35_combat_tuning.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const B=ctx.V8Battle;
assert.strictEqual(typeof B.startPlayerSalvo,'function','V8.3 must keep startPlayerSalvo');
const state=B.newGame();state.spawnT=999;state.playerFireT=999;
const enemy=B.spawnEnemy(state,'gunship',{x:1280,y:560});
B.setFocus(state,enemy);
B.startPlayerSalvo(state,enemy);
B.update(state,.01);
assert.strictEqual(state.shotIndex,1,'salvo must begin with one cannonball, not spawn the whole salvo instantly');
for(let i=0;i<12;i++)B.update(state,.05);
assert.strictEqual(state.shotIndex,2,'active V8.4.1 tuning reduces the salvo to exactly two cannonballs');
assert.strictEqual(state.salvo,null,'reduced salvo must finish cleanly');
console.log('V8.3 salvo compatibility tests passed');
