const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const ctx={console,Math,setTimeout,clearTimeout};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['js/v8/00_v8_base.js','js/v8/10_ship_grid.js','js/v8/20_projectiles.js','js/v8/30_battle.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const B=ctx.V8Battle;
assert.strictEqual(typeof B.startPlayerSalvo,'function','V8.3 must expose startPlayerSalvo');
const state=B.newGame();state.spawnT=999;state.playerFireT=999;
const enemy=B.spawnEnemy(state,'gunship',{x:1280,y:560});
B.setFocus(state,enemy);
B.startPlayerSalvo(state,enemy);
B.update(state,.01);
let playerShots=state.projectiles.filter(p=>p.side==='player');
assert.strictEqual(playerShots.length,1,'salvo must begin with one cannonball, not spawn all four instantly');
for(let i=0;i<8;i++)B.update(state,.05);
playerShots=state.projectiles.filter(p=>p.side==='player');
assert.strictEqual(playerShots.length,4,'one salvo must contain exactly four player cannonballs');
const arcs=playerShots.map(p=>p.arcHeight);
assert(Math.max(...arcs)-Math.min(...arcs)>=12,'salvo cannonballs should have visible arc-height variation');
console.log('V8.3 salvo tests passed');
