const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const ctx={console,Math};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['js/v8/10_ship_grid.js','js/v8/36_damage_model.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const G=ctx.V8ShipGrid;
assert.strictEqual(typeof G.damageStage,'function','damage model must expose damageStage(cell)');
const cell={alive:true,maxHp:60,hp:60};
assert.strictEqual(G.damageStage(cell),'intact');
cell.hp=45;assert.strictEqual(G.damageStage(cell),'cracked');
cell.hp=30;assert.strictEqual(G.damageStage(cell),'critical');
cell.hp=0;cell.alive=false;assert.strictEqual(G.damageStage(cell),'destroyed');
console.log('V8.5 damage stage compatibility tests passed');
