const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const ctx={console,Math,setTimeout,clearTimeout};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['js/v8/00_v8_base.js','js/v8/10_ship_grid.js','js/v8/20_projectiles.js','js/v8/30_battle.js','js/v8/35_combat_tuning.js','js/v8/36_damage_flooding.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const B=ctx.V8Battle,DF=ctx.V8DamageFlooding;
assert.strictEqual(typeof DF.ensureFlooding,'function','V8.5 must expose ensureFlooding');
assert.strictEqual(typeof DF.isWaterlineHull,'function','V8.5 must expose waterline classification');
assert.strictEqual(typeof DF.addLeak,'function','V8.5 must expose addLeak');
assert.strictEqual(typeof DF.updateFlooding,'function','V8.5 must expose updateFlooding');
const state=B.newGame();state.spawnT=999;state.playerFireT=999;
const ship=B.spawnEnemy(state,'gunship',{x:1200,y:560});
const hull=ship.cells.find(c=>c.type==='hull'&&DF.isWaterlineHull(ship,c));
assert(hull,'test ship must have a waterline hull cell');
DF.ensureFlooding(ship);
assert.strictEqual(ship.leaks.length,0);
DF.addLeak(ship,hull);
DF.addLeak(ship,hull);
assert.strictEqual(ship.leaks.length,1,'same breach must not create duplicate leaks');
const drySpeed=ship.speed;
DF.updateFlooding(state,ship,1);
assert(ship.flooding>0,'leak must increase flooding');
assert(ship.draft>0,'flooding must increase draft');
assert(ship.speed<drySpeed,'flooding must reduce ship speed');
ship.flooding=.99;
DF.updateFlooding(state,ship,1);
assert.strictEqual(ship.state,'sink','enemy must sink when flooding reaches 1');

const playerState=B.newGame();
DF.ensureFlooding(playerState.player);playerState.player.flooding=.995;
DF.addLeak(playerState.player,playerState.player.cells.find(c=>c.type==='hull'&&DF.isWaterlineHull(playerState.player,c)));
DF.updateFlooding(playerState,playerState.player,1);
assert.strictEqual(playerState.state,'lose','player must lose when flooding reaches 1');
console.log('V8.5 flooding tests passed');
